// user creation
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const GET_USER_DATA_BY_ID = 'GET_USER_DATA_BY_ID';
export const ADD_SUCCESS_USER_DATA = 'ADD_SUCCESS_USER_DATA';
export const ADD_FAILED_USER_DATA = 'ADD_FAILED_USER_DATA';
export const GET_ALL_USER_DATA = 'GET_ALL_USER_DATA';
export const SUCCESS_USER_LIST_DATA = 'SUCCESS_USER_LIST_DATA';
export const FAILED_USER_LIST_DATA = 'FAILED_USER_LIST_DATA';
export const UPDATE_SUCCESS_USER_DATA = 'UPDATE_SUCCESS_USER_DATA';
export const UPDATE_FAILED_USER_DATA = 'UPDATE_FAILED_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const SUCCESS_GET_USER_DATA_BY_ID = 'SUCCESS_GET_USER_DATA_BY_ID';
export const FAILED_GET_USER_DATA_BY_ID = 'FAILED_GET_USER_DATA_BY_ID';
export const CHECK_USER_DUPLICATE = 'CHECK_USER_DUPLICATE';
export const USER_DUPLICATE = 'USER_DUPLICATE';
export const GET_LAST_MODIFIED_DATE_TIME_USER = 'GET_LAST_MODIFIED_DATE_TIME_USER';
export const SUCCESS_LAST_MODIFIED_DATE_USER = 'SUCCESS_LAST_MODIFIED_DATE_USER';
export const FAILED_LAST_MODIFIED_DATE_USER = 'FAILED_LAST_MODIFIED_DATE_USER';
export const GET_ACTIVE_USERS = 'GET_ACTIVE_USERS';
export const SUCCESS_GET_ACTIVE_USERS = 'SUCCESS_GET_ACTIVE_USERS';
export const FAILED_GET_ACTIVE_USERS = 'FAILED_GET_ACTIVE_USERS';
export const GET_ALL_USER_ROLES = 'GET_ALL_USER_ROLES';
export const SUCCESS_GET_ALL_USER_ROLES = 'SUCCESS_GET_ALL_USER_ROLES';
export const FAILED_GET_ALL_USER_ROLES = 'FAILED_GET_ALL_USER_ROLES';
export const GET_PROFILE_DATA_BY_ID = 'GET_PROFILE_DATA_BY_ID';
export const SUCCESS_GET_PROFILE_DATA_BY_ID = 'SUCCESS_GET_PROFILE_DATA_BY_ID';
export const FAILED_GET_PROFILE_DATA_BY_ID = 'FAILED_GET_PROFILE_DATA_BY_ID';

//user login
export const CHECK_USER_LOGIN_CREDENTIALS = 'CHECK_USER_LOGIN_CREDENTIALS';
export const SUCCESS_USER_LOGIN_DATA = 'SUCCESS_USER_LOGIN_DATA';
export const FAILED_USER_LOGIN_DATA = 'FAILED_USER_LOGIN_DATA';

//forgot password
export const FORGOT_PASSWORD_CREDENTIALS = 'FORGOT_PASSWORD_CREDENTIALS';
export const SUCCESS_FORGOT_PASSWORD_CREDENTIALS = 'SUCCESS_FORGOT_PASSWORD_CREDENTIALS';
export const FAILED_FORGOT_PASSWORD_CREDENTIALS = 'FAILED_FORGOT_PASSWORD_CREDENTIALS';

//reset password
export const RESET_PASSWORD_CREDENTIALS = 'RESET_PASSWORD_CREDENTIALS';
export const SUCCESS_RESET_PASSWORD_CREDENTIALS = 'SUCCESS_RESET_PASSWORD_CREDENTIALS';
export const FAILED_RESET_PASSWORD_CREDENTIALS = 'FAILED_RESET_PASSWORD_CREDENTIALS';

//UPDATE_MY_PROFILE
export const UPDATE_MY_PROFILE = 'UPDATE_MY_PROFILE';
export const SUCCESS_UPDATE_MY_PROFILE = 'SUCCESS_UPDATE_MY_PROFILE';
export const FAILED_UPDATE_MY_PROFILE = 'FAILED_UPDATE_MY_PROFILE';

// clear user
export const CLEAR_USER = 'CLEAR_USER';
export const SUCCESS_CLEAR_USER = 'SUCCESS_CLEAR_USER';
export const FAILED_CLEAR_USER = 'FAILED_CLEAR_USER';
