//bank

export const SAVE_BANK_DATA = 'SAVE_BANK_DATA';
export const GET_BANK_DATA_BY_ID = 'GET_BANK_DATA_BY_ID';
export const ADD_SUCCESS_BANK_DATA = 'ADD_SUCCESS_BANK_DATA';
export const ADD_FAILED_BANK_DATA = 'ADD_FAILED_BANK_DATA';
export const GET_ALL_BANK_DATA = 'GET_ALL_BANK_DATA';
export const SUCCESS_BANK_LIST_DATA = 'SUCCESS_BANK_LIST_DATA';
export const FAILED_BANK_LIST_DATA = 'FAILED_BANK_LIST_DATA';
export const UPDATE_SUCCESS_BANK_DATA = 'UPDATE_SUCCESS_BANK_DATA';
export const UPDATE_FAILED_BANK_DATA = 'UPDATE_FAILED_BANK_DATA';
export const UPDATE_BANK_DATA = 'UPDATE_BANK_DATA';
export const SUCCESS_GET_BANK_DATA_BY_ID = 'SUCCESS_GET_BANK_DATA_BY_ID';
export const FAILED_GET_BANK_DATA_BY_ID = 'FAILED_GET_BANK_DATA_BY_ID';
export const CHECK_BANK_DUPLICATE = 'CHECK_BANK_DUPLICATE';
export const BANK_DUPLICATE = 'BANK_DUPLICATE';
export const GET_LAST_MODIFIED_DATE_TIME_BANK = 'GET_LAST_MODIFIED_DATE_TIME_BANK';
export const SUCCESS_LAST_MODIFIED_DATE_BANK = 'SUCCESS_LAST_MODIFIED_DATE_BANK';
export const FAILED_LAST_MODIFIED_DATE_BANK = 'FAILED_LAST_MODIFIED_DATE_BANK';

//branch

export const SAVE_BRANCH_DATA = 'SAVE_BRANCH_DATA';
export const GET_BRANCH_DATA_BY_ID = 'GET_BRANCH_DATA_BY_ID';
export const ADD_SUCCESS_BRANCH_DATA = 'ADD_SUCCESS_BRANCH_DATA';
export const ADD_FAILED_BRANCH_DATA = 'ADD_FAILED_BRANCH_DATA';
export const GET_ALL_BRANCH_DATA = 'GET_ALL_BRANCH_DATA';
export const SUCCESS_BRANCH_LIST_DATA = 'SUCCESS_BRANCH_LIST_DATA';
export const FAILED_BRANCH_LIST_DATA = 'FAILED_BRANCH_LIST_DATA';
export const UPDATE_SUCCESS_BRANCH_DATA = 'UPDATE_SUCCESS_BRANCH_DATA';
export const UPDATE_FAILED_BRANCH_DATA = 'UPDATE_FAILED_BRANCH_DATA';
export const UPDATE_BRANCH_DATA = 'UPDATE_BRANCH_DATA';
export const SUCCESS_GET_BRANCH_DATA_BY_ID = 'SUCCESS_GET_BRANCH_DATA_BY_ID';
export const FAILED_GET_BRANCH_DATA_BY_ID = 'FAILED_GET_BRANCH_DATA_BY_ID';
export const CHECK_BRANCH_DUPLICATE = 'CHECK_BRANCH_DUPLICATE';
export const BRANCH_DUPLICATE = 'BRANCH_DUPLICATE';
export const GET_LAST_MODIFIED_DATE_TIME_BRANCH = 'GET_LAST_MODIFIED_DATE_TIME_BRANCH';
export const SUCCESS_LAST_MODIFIED_DATE_BRANCH = 'SUCCESS_LAST_MODIFIED_DATE_BRANCH';
export const FAILED_LAST_MODIFIED_DATE_BRANCH = 'FAILED_LAST_MODIFIED_DATE_BRANCH';
export const GET_BRANCHES_BY_BANK_ID = 'GET_BRANCHES_BY_BANK_ID';
export const SUCCESS_GET_BRANCHES_BY_BANK_ID = 'SUCCESS_GET_BRANCHES_BY_BANK_ID';
export const FAILED_GET_BRANCHES_BY_BANK_ID = 'FAILED_GET_BRANCHES_BY_BANK_ID';
export const CHECKED_SAVED_BANK_AND_BRANCH = 'CHECKED_SAVED_BANK_AND_BRANCH';
export const SAVED_BANK_AND_BRANCH = 'SAVED_BANK_AND_BRANCH';

//bank details
export const SAVE_BANK_DETAILS_DATA = 'SAVE_BANK_DETAILS_DATA';
export const GET_BANK_DETAILS_DATA_BY_ID = 'GET_BANK_DETAILS_DATA_BY_ID';
export const ADD_SUCCESS_DETAILS_BANK_DATA = 'ADD_SUCCESS_DETAILS_BANK_DATA';
export const ADD_FAILED_DETAILS_BANK_DATA = 'ADD_FAILED_DETAILS_BANK_DATA';
export const GET_ALL_BANK_DETAILS_DATA = 'GET_ALL_BANK_DETAILS_DATA';
export const SET_BANK_DETAILS_LIST = 'SET_BANK_DETAILS_LIST';
export const SUCCESS_BANK_DETAILS_LIST_DATA = 'SUCCESS_BANK_DETAILS_LIST_DATA';
export const FAILED_BANK_DETAILS_LIST_DATA = 'FAILED_BANK_DETAILS_LIST_DATA';
export const UPDATE_SUCCESS_BANK_DETAILS_DATA = 'UPDATE_SUCCESS_BANK_DETAILS_DATA';
export const UPDATE_FAILED_BANK_DETAILS_DATA = 'UPDATE_FAILED_BANK_DETAILS_DATA';
export const UPDATE_BANK_DETAILS_DATA = 'UPDATE_BANK_DETAILS_DATA';
export const SUCCESS_GET_BANK_DETAILS_DATA_BY_ID = 'SUCCESS_GET_BANK_DETAILS_DATA_BY_ID';
export const FAILED_GET_BANK_DETAILS_DATA_BY_ID = 'FAILED_GET_BANK_DETAILS_DATA_BY_ID';
export const CHECK_BANK_DETAILS_DUPLICATE = 'CHECK_BANK_DETAILS_DUPLICATE';
export const BANK_DETAILS_DUPLICATE = 'BANK_DETAILS_DUPLICATE';
export const GET_LAST_MODIFIED_DATE_TIME_BANK_DETAILS = 'GET_LAST_MODIFIED_DATE_TIME_BANK_DETAILS';
export const SUCCESS_LAST_MODIFIED_DATE_BANK_DETAILS = 'SUCCESS_LAST_MODIFIED_DATE_BANK_DETAILS';
export const FAILED_LAST_MODIFIED_DATE_BANK_DETAILS = 'FAILED_LAST_MODIFIED_DATE_BANK_DETAILS';
