// EXCHNAGE_RATE_TYPE set up
export const SAVE_EXCHNAGE_RATE_TYPE_DATA = 'SAVE_EXCHNAGE_RATE_TYPE_DATA';
export const GET_EXCHNAGE_RATE_TYPE_BY_ID = 'GET_EXCHNAGE_RATE_TYPE_BY_ID';
export const ADD_SUCCESS_EXCHNAGE_RATE_TYPE_DATA = 'ADD_SUCCESS_EXCHNAGE_RATE_TYPE_DATA';
export const ADD_FAILED_EXCHNAGE_RATE_TYPE_DATA = 'ADD_FAILED_EXCHNAGE_RATE_TYPE_DATA';
export const GET_ALL_EXCHNAGE_RATE_TYPE_DATA = 'GET_ALL_EXCHNAGE_RATE_TYPE_DATA';
export const SUCCESS_EXCHNAGE_RATE_TYPE_LIST_DATA = 'SUCCESS_EXCHNAGE_RATE_TYPE_LIST_DATA';
export const FAILED_EXCHNAGE_RATE_TYPE_LIST_DATA = 'FAILED_EXCHNAGE_RATE_TYPE_LIST_DATA';
export const UPDATE_SUCCESS_EXCHNAGE_RATE_TYPE_DATA = 'UPDATE_SUCCESS_EXCHNAGE_RATE_TYPE_DATA';
export const UPDATE_FAILED_EXCHNAGE_RATE_TYPE_DATA = 'UPDATE_FAILED_EXCHNAGE_RATE_TYPE_DATA';
export const UPDATE_EXCHNAGE_RATE_TYPE_DATA = 'UPDATE_EXCHNAGE_RATE_TYPE_DATA';
export const SUCCESS_GET_EXCHNAGE_RATE_TYPE_DATA_BY_ID = 'SUCCESS_GET_EXCHNAGE_RATE_TYPE_DATA_BY_ID';
export const FAILED_GET_EXCHNAGE_RATE_TYPE_DATA_BY_ID = 'FAILED_GET_EXCHNAGE_RATE_TYPE_DATA_BY_ID';
export const CHECK_EXCHNAGE_RATE_TYPE_DUPLICATE = 'CHECK_EXCHNAGE_RATE_TYPE_DUPLICATE';
export const EXCHNAGE_RATE_TYPE_DUPLICATE = 'EXCHNAGE_RATE_TYPE_DUPLICATE';
