export const SAVE_HOTEL_MAIN_DATA = 'SAVE_HOTEL_MAIN_DATA';
export const GET_HOTEL_MAIN_DATA_BY_ID = 'GET_HOTEL_MAIN_DATA_BY_ID';
export const ADD_SUCCESS_HOTEL_MAIN_DATA = 'ADD_SUCCESS_HOTEL_MAIN_DATA';
export const ADD_FAILED_HOTEL_MAIN_DATA = 'ADD_FAILED_HOTEL_MAIN_DATA';
export const GET_ALL_HOTEL_MAIN_DATA = 'GET_ALL_HOTEL_MAIN_DATA';
export const SET_HOTEL_MAIN_LIST = 'SET_HOTEL_MAIN_LIST';
export const SUCCESS_HOTEL_MAIN_LIST_DATA = 'SUCCESS_HOTEL_MAIN_LIST_DATA';
export const FAILED_HOTEL_MAIN_LIST_DATA = 'FAILED_HOTEL_MAIN_LIST_DATA';
export const UPDATE_SUCCESS_HOTEL_MAIN_DATA = 'UPDATE_SUCCESS_HOTEL_MAIN_DATA';
export const UPDATE_FAILED_HOTEL_MAIN_DATA = 'UPDATE_FAILED_HOTEL_MAIN_DATA';
export const UPDATE_HOTEL_MAIN_DATA = 'UPDATE_HOTEL_MAIN_DATA';
export const SUCCESS_GET_HOTEL_MAIN_DATA_BY_ID = 'SUCCESS_GET_HOTEL_MAIN_DATA_BY_ID';
export const FAILED_GET_HOTEL_MAIN_DATA_BY_ID = 'FAILED_GET_HOTEL_MAIN_DATA_BY_ID';
export const CHECK_HOTEL_MAIN_DUPLICATE = 'CHECK_HOTEL_MAIN_DUPLICATE';
export const HOTEL_MAIN_DUPLICATE = 'HOTEL_MAIN_DUPLICATE';
export const GET_LAST_MODIFIED_DATE_TIME_HOTEL_MAIN = 'GET_LAST_MODIFIED_DATE_TIME_HOTEL_MAIN';
export const SUCCESS_LAST_MODIFIED_DATE_HOTEL_MAIN = 'SUCCESS_LAST_MODIFIED_DATE_HOTEL_MAIN';
export const FAILED_LAST_MODIFIED_DATE_HOTEL_MAIN = 'FAILED_LAST_MODIFIED_DATE_HOTEL_MAIN';

export const GET_ALL_ACTIVE_HOTEL_MAIN_DATA = 'GET_ALL_ACTIVE_HOTEL_MAIN_DATA';
export const SUCCESS_ACTIVE_HOTEL_MAIN_LIST_DATA = 'SUCCESS_ACTIVE_HOTEL_MAIN_LIST_DATA';
export const FAILED_ACTIVE_HOTEL_MAIN_LIST_DATA = 'FAILED_ACTIVE_HOTEL_MAIN_LIST_DATA';

export const GET_HOTELS_BY_LOCATION_CURRENCY_MIN_MAX = 'GET_HOTELS_BY_LOCATION_CURRENCY_MIN_MAX';
export const SUCCESS_GET_HOTELS_BY_LOCATION_CURRENCY_MIN_MAX = 'SUCCESS_GET_HOTELS_BY_LOCATION_CURRENCY_MIN_MAX';
export const FAILED_GET_HOTELS_BY_LOCATION_CURRENCY_MIN_MAX = 'FAILED_GET_HOTELS_BY_LOCATION_CURRENCY_MIN_MAX';
