//hotel facility types
export const GET_ALL_HOTEL_FACILITY_TYPES_DATA = 'GET_ALL_HOTEL_FACILITY_TYPES_DATA';
export const SUCCESS_HOTEL_FACILITY_TYPES_LIST_DATA = 'SUCCESS_HOTEL_FACILITY_TYPES_LIST_DATA';
export const FAILED_HOTEL_FACILITY_TYPES_LIST_DATA = 'FAILED_HOTEL_FACILITY_TYPES_LIST_DATA';

//hotel facility
export const SAVE_HOTEL_FACILITY_DATA = 'SAVE_HOTEL_FACILITY_DATA';
export const GET_HOTEL_FACILITY_DATA_BY_ID = 'GET_HOTEL_FACILITY_DATA_BY_ID';
export const ADD_SUCCESS_HOTEL_FACILITY_DATA = 'ADD_SUCCESS_HOTEL_FACILITY_DATA';
export const ADD_FAILED_HOTEL_FACILITY_DATA = 'ADD_FAILED_HOTEL_FACILITY_DATA';
export const GET_ALL_HOTEL_FACILITY_DATA = 'GET_ALL_HOTEL_FACILITY_DATA';
export const SET_HOTEL_FACILITY_LIST = 'SET_HOTEL_FACILITY_LIST';
export const SUCCESS_HOTEL_FACILITY_LIST_DATA = 'SUCCESS_HOTEL_FACILITY_LIST_DATA';
export const FAILED_HOTEL_FACILITY_LIST_DATA = 'FAILED_HOTEL_FACILITY_LIST_DATA';
export const UPDATE_SUCCESS_HOTEL_FACILITY_DATA = 'UPDATE_SUCCESS_HOTEL_FACILITY_DATA';
export const UPDATE_FAILED_HOTEL_FACILITY_DATA = 'UPDATE_FAILED_HOTEL_FACILITY_DATA';
export const UPDATE_HOTEL_FACILITY_DATA = 'UPDATE_HOTEL_FACILITY_DATA';
export const SUCCESS_GET_HOTEL_FACILITY_DATA_BY_ID = 'SUCCESS_GET_HOTEL_FACILITY_DATA_BY_ID';
export const FAILED_GET_HOTEL_FACILITY_DATA_BY_ID = 'FAILED_GET_HOTEL_FACILITY_DATA_BY_ID';
export const CHECK_HOTEL_FACILITY_DUPLICATE = 'CHECK_HOTEL_FACILITY_DUPLICATE';
export const HOTEL_FACILITY_DUPLICATE = 'HOTEL_FACILITY_DUPLICATE';
export const GET_LAST_MODIFIED_DATE_TIME_HOTEL_FACILITY = 'GET_LAST_MODIFIED_DATE_TIME_HOTEL_FACILITY';
export const SUCCESS_LAST_MODIFIED_DATE_HOTEL_FACILITY = 'SUCCESS_LAST_MODIFIED_DATE_HOTEL_FACILITY';
export const FAILED_LAST_MODIFIED_DATE_HOTEL_FACILITY = 'FAILED_LAST_MODIFIED_DATE_HOTEL_FACILITY';

export const GET_ALL_ACTIVE_ROOM_RECREATION_DATA = 'GET_ALL_ACTIVE_ROOM_RECREATION_DATA';
export const SUCCESS_ACTIVE_ROOM_RECREATION_LIST_DATA = 'SUCCESS_ACTIVE_ROOM_RECREATION_LIST_DATA';
export const FAILED_ACTIVE_ROOM_RECREATION_LIST_DATA = 'FAILED_ACTIVE_ROOM_RECREATION_LIST_DATA';

export const GET_ALL_ACTIVE_FACILITIES_OFFERED_DATA = 'GET_ALL_ACTIVE_FACILITIES_OFFERED_DATA';
export const SUCCESS_ACTIVE_FACILITIES_OFFERED_LIST_DATA = 'SUCCESS_ACTIVE_FACILITIES_OFFERED_LIST_DATA';
export const FAILED_ACTIVE_FACILITIES_OFFERED_LIST_DATA = 'FAILED_ACTIVE_FACILITIES_OFFERED_LIST_DATA';

export const GET_ALL_ACTIVE_CHILDREN_FACILITIES_DATA = 'GET_ALL_ACTIVE_CHILDREN_FACILITIES_DATA';
export const SUCCESS_ACTIVE_CHILDREN_FACILITIES_LIST_DATA = 'SUCCESS_ACTIVE_CHILDREN_FACILITIES_LIST_DATA';
export const FAILED_ACTIVE_CHILDREN_FACILITIES_LIST_DATA = 'FAILED_ACTIVE_CHILDREN_FACILITIES_LIST_DATA';

export const GET_ALL_ACTIVE_SERVICE_OFFERED_DATA = 'GET_ALL_ACTIVE_SERVICE_OFFERED_DATA';
export const SUCCESS_ACTIVE_SERVICE_OFFERED_LIST_DATA = 'SUCCESS_ACTIVE_SERVICE_OFFERED_LIST_DATA';
export const FAILED_ACTIVE_SERVICE_OFFERED_LIST_DATA = 'FAILED_ACTIVE_SERVICE_OFFERED_LIST_DATA';
