//tranport rate
export const SAVE_TRANSPORT_RATE_DATA = 'SAVE_TRANSPORT_RATE_DATA';
export const GET_TRANSPORT_RATE_DATA_BY_ID = 'GET_TRANSPORT_RATE_DATA_BY_ID';
export const ADD_SUCCESS_TRANSPORT_RATE_DATA = 'ADD_SUCCESS_TRANSPORT_RATE_DATA';
export const ADD_FAILED_TRANSPORT_RATE_DATA = 'ADD_FAILED_TRANSPORT_RATE_DATA';
export const GET_ALL_TRANSPORT_RATE_DATA = 'GET_ALL_TRANSPORT_RATE_DATA';
export const SET_TRANSPORT_RATE_LIST = 'SET_TRANSPORT_RATE_LIST';
export const SUCCESS_TRANSPORT_RATE_LIST_DATA = 'SUCCESS_TRANSPORT_RATE_LIST_DATA';
export const FAILED_TRANSPORT_RATE_LIST_DATA = 'FAILED_TRANSPORT_RATE_LIST_DATA';
export const UPDATE_SUCCESS_TRANSPORT_RATE_DATA = 'UPDATE_SUCCESS_TRANSPORT_RATE_DATA';
export const UPDATE_FAILED_TRANSPORT_RATE_DATA = 'UPDATE_FAILED_TRANSPORT_RATE_DATA';
export const UPDATE_TRANSPORT_RATE_DATA = 'UPDATE_TRANSPORT_RATE_DATA';
export const SUCCESS_GET_TRANSPORT_RATE_DATA_BY_ID = 'SUCCESS_GET_TRANSPORT_RATE_DATA_BY_ID';
export const FAILED_GET_TRANSPORT_RATE_DATA_BY_ID = 'FAILED_GET_TRANSPORT_RATE_DATA_BY_ID';
export const CHECK_TRANSPORT_RATE_DUPLICATE = 'CHECK_TRANSPORT_RATE_DUPLICATE';
export const TRANSPORT_RATE_DUPLICATE = 'TRANSPORT_RATE_DUPLICATE';
export const GET_LAST_MODIFIED_DATE_TIME_TRANSPORT_RATE = 'GET_LAST_MODIFIED_DATE_TIME_TRANSPORT_RATE';
export const SUCCESS_LAST_MODIFIED_DATE_TRANSPORT_RATE = 'SUCCESS_LAST_MODIFIED_DATE_TRANSPORT_RATE';
export const FAILED_LAST_MODIFIED_DATE_TRANSPORT_RATE = 'FAILED_LAST_MODIFIED_DATE_TRANSPORT_RATE';

//mode of transport
export const GET_ALL_MODE_OF_TRANSPORT_DATA = 'GET_ALL_MODE_OF_TRANSPORT_DATA';
export const SUCCESS_MODE_OF_TRANSPORT_LIST_DATA = 'SUCCESS_MODE_OF_TRANSPORT_LIST_DATA';
export const FAILED_MODE_OF_TRANSPORT_LIST_DATA = 'FAILED_MODE_OF_TRANSPORT_LIST_DATA';

//charge method
export const GET_ALL_CHARGE_METHOD_DATA = 'GET_ALL_CHARGE_METHOD_DATA';
export const SUCCESS_CHARGE_METHOD_LIST_DATA = 'SUCCESS_CHARGE_METHOD_LIST_DATA';
export const FAILED_CHARGE_METHOD_LIST_DATA = 'FAILED_CHARGE_METHOD_LIST_DATA';
