export const SAVE_DISTANCE_DATA = 'SAVE_DISTANCE_DATA';
export const ADD_SUCCESS_DISTANCE_DATA = 'ADD_SUCCESS_DISTANCE_DATA';
export const ADD_FAILED_DISTANCE_DATA = 'ADD_FAILED_DISTANCE_DATA';
export const GET_ALL_DISTANCE_DATA = 'GET_ALL_DISTANCE_DATA';
export const SUCCESS_DISTANCE_LIST_DATA = 'SUCCESS_DISTANCE_LIST_DATA';
export const FAILED_DISTANCE_LIST_DATA = 'FAILED_DISTANCE_LIST_DATA';
export const GET_DISTANCE_DATA_BY_ID = 'GET_DISTANCE_DATA_BY_ID';
export const SUCCESS_GET_DISTANCE_DATA_BY_ID = 'SUCCESS_GET_DISTANCE_DATA_BY_ID';
export const FAILED_GET_DISTANCE_DATA_BY_ID = 'FAILED_GET_DISTANCE_DATA_BY_ID';
export const UPDATE_DISTANCE_DATA = 'UPDATE_DISTANCE_DATA';
export const UPDATE_SUCCESS_DISTANCE_DATA = 'UPDATE_SUCCESS_DISTANCE_DATA';
export const UPDATE_FAILED_DISTANCE_DATA = 'UPDATE_FAILED_DISTANCE_DATA';
export const CHECK_DISTANCE_CODE_DUPLICATE = 'CHECK_DISTANCE_CODE_DUPLICATE';
export const DISTANCE_CODE_DUPLICATE = 'DISTANCE_CODE_DUPLICATE';
export const GET_DISTANCE_LAST_MODIFIED_DATE_TIME = 'GET_DISTANCE_LAST_MODIFIED_DATE_TIME';
export const SUCCESS_LAST_MODIFIED_DATE_DISTANCE = 'SUCCESS_LAST_MODIFIED_DATE_DISTANCE';
export const FAILED_LAST_MODIFIED_DATE_DISTANCE = 'FAILED_LAST_MODIFIED_DATE_DISTANCE';

export const GET_ALL_ACTIVE_DISTANCE_DATA_TBY_TRANSPORT_TYPE = 'GET_ALL_ACTIVE_DISTANCE_DATA_TBY_TRANSPORT_TYPE';
export const SUCCESS_GET_ALL_ACTIVE_DISTANCE_DATA_TBY_TRANSPORT_TYPE = 'SUCCESS_ET_ALL_ACTIVE_DISTANCE_DATA_TBY_TRANSPORT_TYPE';
export const FAILED_GET_ALL_ACTIVE_DISTANCE_DATA_TBY_TRANSPORT_TYPE = 'FAILED_GET_ALL_ACTIVE_DISTANCE_DATA_TBY_TRANSPORT_TYPE';

export const GET_CALCULATED_DISTANCE_AND_DURATION = 'GET_CALCULATED_DISTANCE_AND_DURATION';
export const SUCCESS_GET_CALCULATED_DISTANCE_AND_DURATION = 'SUCCESS_GET_CALCULATED_DISTANCE_AND_DURATION';
export const FAILED_GET_CALCULATED_DISTANCE_AND_DURATION = 'FAILED_GET_CALCULATED_DISTANCE_AND_DURATION';
