//currency
export const GET_ALL_CURRENCIES = 'GET_ALL_CURRENCIES';
export const SUCCESS_CURRENCY_LIST_DATA = 'SUCCESS_CURRENCY_LIST_DATA';
export const FAILED_CURRENCY_LIST_DATA = 'FAILED_CURRENCY_LIST_DATA';
